---
- hosts: all
  become: yes
  tasks:
  - name: uninstall httpd Webserver
    package: 
     name: httpd
     state: present
  
  - name: Start httpd service
    service: 
      name: httpd
      state: started
      enable: yes
    

